### ISSUE TITLE
0.8.1 is labeled as 0.8.0 in MelonInfo.

### ISSUE THREAD

**Issue by plaistow11** [Astrum-Project/AstralCore#4]
On 0.8.1, it is still called 0.8.0 in the MelonInfo, thus causing confusion to users trying to fix problems.

**Comment by xKiraiChan** [comment]
When the 0.8.1 fix was created I was on linux and unable to compile the mod myself, the person that fixed it for me forgot the update the version.
On the next update I will bump the version to 0.8.2 but there isn't much I can do currently

**Comment by xKiraiChan** [comment]
I've updated the old 0.8.1 release but I doubt anyone will download the fix
